In [120]:
import requests
import json
import pandas as pd
size= 50000#max 500
cursor = 0
df = pd.DataFrame()
count =0
#while count<2:
while True:
    count = count+1
    url=f"https://opendata.rdw.nl/resource/m9d7-ebf2.json?$limit={size}&$offset={cursor}"
    response = requests.get(url)
    resp = response.json()
    items = pd.DataFrame(resp)
    df = df.append(items)
    print(f"offset: {cursor}\t, size: {size}\t, count:{count}")
    cursor += size
    if len(resp)==0:
        break

df.head()

offset: 0	, size: 500	, count:1
offset: 500	, size: 500	, count:2

,kenteken,voertuigsoort,merk,handelsbenaming,vervaldatum_apk,datum_tenaamstelling,bruto_bpm,inrichting,aantal_zitplaatsen,eerste_kleur,...,plaats_chassisnummer,zuinigheidslabel,type_gasinstallatie,maximale_constructiesnelheid_brom_snorfiets,vermogen_brom_snorfiets,europese_voertuigcategorie_toevoeging,europese_uitvoeringcategorie_toevoeging,vervaldatum_tachograaf,oplegger_geremd,aantal_staanplaatsen
0,G398XT,Personenauto,RENAULT,CLIO,20240110,20200110,2466,hatchback,5,BLAUW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,86BLPK,Bedrijfsauto,RENAULT,KANGOO 1.5 DCI 80 EURO 2000,20220205,20180208,NaN,gesloten opbouw,2,N.v.t.,...,onder r. voorzitting op dwarsbalk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GK039H,Personenauto,MITSUBISHI,MITSUBISHI SPACE STAR,20230617,20150616,1357,hatchback,5,WIT,...,r. motorruimte,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5223WH,Aanhangwagen,VAR,VAR II,NaN,20090109,NaN,veewagen,NaN,N.v.t.,...,op trekboom 080 cm a. hart koppeling,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,47WVVK,Middenasaanhangwagen,HENRA,PL27C/SL,NaN,20200410,NaN,neerklapbare zijschotten,NaN,N.v.t.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [121]:
df.rename(columns={'kenteken': 'plate'}, inplace=True)
df.rename(columns={'merk': 'make'}, inplace=True)
df.rename(columns={'handelsbenaming': 'model'}, inplace=True)

df.rename(columns={'lengte': 'length'}, inplace=True)
df.rename(columns={'breedte': 'width'}, inplace=True)
df.rename(columns={'inrichting': 'type'}, inplace=True)
df.rename(columns={'voertuigsoort': 'kind'}, inplace=True)

df.drop(['datum_tenaamstelling','vervaldatum_apk','bruto_bpm','eerste_kleur','tweede_kleur',
         'aantal_cilinders','massa_ledig_voertuig','toegestane_maximum_massa_voertuig',
         'massa_rijklaar','datum_eerste_toelating','datum_eerste_afgifte_nederland','wacht_op_keuren',
         'wam_verzekerd','laadvermogen','aantal_wielen','aantal_zitplaatsen','cilinderinhoud',
         'zuinigheidslabel','catalogusprijs','aantal_deuren','afstand_hart_koppeling_tot_achterzijde_voertuig',
         'afstand_voorzijde_voertuig_tot_hart_koppeling','maximum_massa_trekken_ongeremd',
         'aanhangwagen_autonoom_geremd','aanhangwagen_middenas_geremd','europese_voertuigcategorie',
         'technische_max_massa_voertuig','maximum_trekken_massa_geremd','plaats_chassisnummer','typegoedkeuringsnummer',
         'variant','uitvoering','volgnummer_wijziging_eu_typegoedkeuring','vermogen_massarijklaar','wielbasis',
         'export_indicator','openstaande_terugroepactie_indicator','taxi_indicator','maximum_massa_samenstelling',
         'aantal_rolstoelplaatsen','jaar_laatste_registratie_tellerstand','tellerstandoordeel',
         'code_toelichting_tellerstandoordeel','tenaamstellen_mogelijk','api_gekentekende_voertuigen_assen',
         'api_gekentekende_voertuigen_brandstof','api_gekentekende_voertuigen_carrosserie',
         'api_gekentekende_voertuigen_carrosserie_specifiek','api_gekentekende_voertuigen_voertuigklasse',
         'maximale_constructiesnelheid_brom_snorfiets','vermogen_brom_snorfiets','europese_voertuigcategorie_toevoeging',
         'europese_uitvoeringcategorie_toevoeging','type_gasinstallatie','oplegger_geremd','vervaldatum_tachograaf'
         ,'aantal_staanplaatsen'
         
         ], axis=1, inplace=True)

df.rename(columns={'maximum_ondersteunende_snelheid': 'beep'}, inplace=True)
df.rename(columns={'afwijkende_maximum_snelheid': 'tuut'}, inplace=True)

for col in df.columns:
    print(col)
df.head()

plate
kind
make
model
type
length
width
type
beep

,plate,kind,make,model,type,length,width,type,beep
0,G398XT,Personenauto,RENAULT,CLIO,hatchback,405,173,RJA,0
1,86BLPK,Bedrijfsauto,RENAULT,KANGOO 1.5 DCI 80 EURO 2000,gesloten opbouw,0,166,NaN,NaN
2,GK039H,Personenauto,MITSUBISHI,MITSUBISHI SPACE STAR,hatchback,371,0,A00,NaN
3,5223WH,Aanhangwagen,VAR,VAR II,veewagen,NaN,210,NaN,NaN
4,47WVVK,Middenasaanhangwagen,HENRA,PL27C/SL,neerklapbare zijschotten,556,191,PL2,NaN

In [122]:
df.to_csv("../data/rdw.zip", 
           index=False, 
           compression="zip")